logging:
  level:
    ROOT: INFO
    com.luvina.la: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    # jdbc properties to connect to database
    jdbcUrl: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: admin123
    isAutoCommit: false
    connectionTimeout: 10000
    maximumPoolSize: 20
    leakDetectionThreshold: 64800
    poolName: spring-boot-hikari-mysql-cp
    maxLifetime: 72000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

management:
    endpoint.metrics.enabled: true
    endpoints.web.exposure.include: metrics
